apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: patient-data-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cloudsql-proxy
    spec:
      containers:
        - image: gcr.io/cloudsql-docker/gce-proxy:1.11
          name: cloudsql-proxy
          command: ["/cloud_sql_proxy",
                    "-instances=sema4-test:us-east1:patient-account-data=tcp:3306"]
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
        - image: gcr.io/sema4-test/patientdataimage:latest
          name: gd-deploy-image
          env:
            - name: SECRET_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: username
            - name: SECRET_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: password
          ports:
              - containerPort: 8080
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
        - name: cloudsql
          emptyDir:

